### ISSUE TITLE
Use with H2O

### ISSUE THREAD

**Issue by jwoertink** [Anyolite/anyolite#1] opened 2020-08-25 17:55 UTC
This project is pretty sweet! My first thought was "I wonder how this could be used to integrate with [H2O](https://h2o.examp1e.net/configure/mruby.html)". I'm sure this is still in earlyish stages and just for fun, but being able to throw H2O in front of a crystal web app with easy access to write some crystal middleware that hooks in would be a pretty amazing use for this.

**Comment by Hadeweka** [comment] 2020-08-26 11:01
Thank you very much!

I am not really an expert in web development and haven't used H2O yet, so I can't really tell whether it is possible or not, but I assume it should be. Anyolite has no direct dependencies besides mruby, which is cloned and installed locally, but it is also technically possible to use an existing mruby interpreter (requiring slight modifications to Anyolite).

Maybe you could specify what exactly you have in mind (the link throws a certificate error for me) or what you expect from Anyolite, then I might tell a little more about the feasibility.

**Comment by jwoertink** [comment] 2020-08-26 15:17
wow, that certificate must have just happened. Ok, so H2O is a ridiculously fast web server. There's a small web framework in Ruby called Sinatra, and with it you can easily get 6k requests/second from a simple page. I ported sort of mock version of sinatra to mruby, and stuck H2O in front of it and got [42k req/sec](https://github.com/jwoertink/ruby-in-water). H2O hooks in because it has native mruby support using yaml configs like:

```
hosts:
  "0.0.0.0:9292":
    paths:
      /:
        file.dir: .
        mruby.handler-file: app/api.rb
```

So this tells H2O when someone hits the home page, proxy the request to the `app/api.rb` file. My thought was, what if this proxied to `app/api.cr` instead 😬  A port of sinatra was done in crystal called [kemal](https://kemalcr.com/) which already has an amazing performance boost. I wonder if by sticking H2O in front of kemal, if you could double it. 🤔  

I'll keep watching the project and maybe with some free time later I'll see if I can hack something together.

Thanks!

**Comment by Hadeweka** [comment] 2020-08-26 20:57
I think I see what your idea is.

But is mruby really required, then?
If I understand it correctly, wouldn't it be more useful to bind H2O directly to Crystal?

Of course, keeping the mruby component would allow for more flexibility (in which case a modified Anyolite should work fine), at the cost of some speed due to the Ruby code.

If you need any major modifications to Anyolite, feel free to make an issue with a feature request or a pull request, so I can see what I can do.

**Comment by wyhaines** [comment] 2021-04-01 15:21
H2O embeds mruby. It allows the use of the embedded mruby  to broadly customize its behavior, from request handling and dispatch to access controls to log handling, and much more.

@jwoertink is thinking that if it were possible to integrate Crystal into it, even greater performance could be realized.

**Comment by drhuffman12** [comment] 2021-08-29 02:59
There is an older shard (2018) for H2O at https://github.com/S-YOU/h2o.cr . That might be worth looking into; maybe?

**Comment by Hadeweka** [comment] 2022-05-18 16:03
I will close this issue now, since nobody posted here for a while (and it is not a bug).

If you wish to further discuss this topic, feel free to open a dedicated discussion thread.

**Closed by Hadeweka** 2022-05-18 16:03 UTC
Labels: discussion
